remote_files:
  - filename: "ALL.chr1.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr1.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    checksum: "d259ae8ba408048e9b793dd70970fde5d426e8f165464d5e6bdee7963f27c4b9"
  - filename: "ALL.chr2.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr2.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    checksum: "537f740d03c872933310523d8b06e896ef166b70d546b2cfeab1ceee0bc566dd"
  - filename: "ALL.chr3.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr3.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    checksum: "8ad55cd4e47512c365431a36274f94ec5a6df0db6bf2e1a9b865692eb8c3270d"
  - filename: "ALL.chr4.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr4.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    checksum: "630228658cebc54f82716b9df511ee418ead88010487695d24553340ee8d950b"
  - filename: "ALL.chr5.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr5.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    checksum: "3b9341901d5aa42bc15c6cc87d683dac4f1e1591dd82a4bb7c78c5081ef85227"
  - filename: "ALL.chr6.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr6.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    checksum: "f54a80c00fbfbe3e89a9e877d382e4f8afad4911597ad79bdcaa9db51f44c983"
  - filename: "ALL.chr7.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr7.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    checksum: "f67f9531b34b278a25a450216bc2609251bbe15d91cc0a4b67dcb02e110631f8"
  - filename: "ALL.chr8.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr8.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    checksum: "55e2ff63b4e67b816d4584f7f9775714beff63c6bf3bb3e614ed9402044ea4e8"
  - filename: "ALL.chr9.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr9.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    checksum: "ada97534be62e5153822257bc17c2436eed16c3494c8e83bc7cd8be690b2afc1"
  - filename: "ALL.chr10.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr10.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    checksum: "b3d73ae3e6c3999ddc1fba4bf4322e07bdc225b54f5d4603eabc9f67ec10ff54"
  - filename: "ALL.chr11.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr11.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    checksum: "64b9f63f6d3b5056f60cb297016d9da169e0668083620e4819c934259cd5b6d1"
  - filename: "ALL.chr12.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr12.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    checksum: "05845d1e5b8720a27298ddebaf76234744d308916d97f54355cf98a1f9962fc5"
  - filename: "ALL.chr13.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr13.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    checksum: "564ebefc96e4b5c795979eebc81d57aca11b1b61ddec8085772864e227824f8d"
  - filename: "ALL.chr14.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr14.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    checksum: "e39a17eb5004440697f27678c8a67b80054d880bb20a58ccde341cb34a4b7378"
  - filename: "ALL.chr15.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr15.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    checksum: "79c35fdbc2eb00ef8220c7825283851e2aed14a56704b5f9c7f9156f99e96ef0"
  - filename: "ALL.chr16.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr16.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    checksum: "9c021e589e619c77d0efdfb3ad9bf89752d32cd9b3916d2efb88168dbeef6284"
  - filename: "ALL.chr17.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr17.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    checksum: "dd7082883b50aac8126c6e9864158cd875c5a60780f1bff700ce9cb85d0383c1"
  - filename: "ALL.chr18.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr18.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    checksum: "820017d0708a8beb856c997470ba06bd9e39e886b3818a6f398a6e6159cd1c2c"
  - filename: "ALL.chr19.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr19.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    checksum: "26683a440906e6a789636ccff4b039e923a5c7d31bde50351a760e494c1bf0c3"
  - filename: "ALL.chr20.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr20.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    checksum: "1bbddc1eac3b35d9408bdfb435632126614a7ac89d32d27aa30db6dc94600fec"
  - filename: "ALL.chr21.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr21.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    checksum: "1942e0709625d77928b191e5a1bfbf523aad2fee1764994a599ae4623305cace"
  - filename: "ALL.chr22.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr22.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz"
    checksum: "a90c16c4ff2b3196476d506ae13cb3047fae8670163c7c932c4b0239aef3daf5"
  - filename: "ALL.chr1.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr1.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    checksum: "b7ebe6ef55617b4d28d2f804669fcb4d0e045fd6bad547eac0553aefde2e1853"
  - filename: "ALL.chr2.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr2.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    checksum: "de9cbe172468d433ecbf6f451d9eec256c1291274f61f6f51443a57cc906e8e7"
  - filename: "ALL.chr3.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr3.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    checksum: "e993b87848124792f6d5bf53f8e0646bfe10861d82e32f34b179d2af12339682"
  - filename: "ALL.chr4.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr4.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    checksum: "67cf2d237734e0daef466b66456bd59b2947ae75fd7f42ec752c4c1e2aaab5e1"
  - filename: "ALL.chr5.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr5.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    checksum: "5105dda85ae2a9628ea637e6a611c283699746270d1f0f682c68346ba64d05b4"
  - filename: "ALL.chr6.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr6.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    checksum: "ad04b3635c4d99959ee6810bf030fecdc08291058946aabc9e962fa1248fa275"
  - filename: "ALL.chr7.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr7.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    checksum: "9bb1ee9423f293241d86f8b8e76f80e3f42c8deb5c3ffa7ad7fc495024baeb44"
  - filename: "ALL.chr8.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr8.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    checksum: "838be68a093e4f8d114335634798b181ec218930422fda0c8bb8c04bd0388439"
  - filename: "ALL.chr9.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr9.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    checksum: "6d7f97d8c5f21b79b467ae368957516aead136fdc8fd47b09fc3f7c6d927035e"
  - filename: "ALL.chr10.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr10.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    checksum: "3ef8aa430d5552c2a43cffaa47a1d33f3542dafa41c281c9ee5cdbf416821d96"
  - filename: "ALL.chr11.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr11.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    checksum: "c90c12a81c28502dfa0d2402ef24b39a7384a9b59482feb35f9226d151b148be"
  - filename: "ALL.chr12.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr12.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    checksum: "eb3cded77394dbcf60e354828261703711f68d557274f32b5192de29efb99e8a"
  - filename: "ALL.chr13.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr13.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    checksum: "49b7826f27dd72a3f83221ee117a1f9571ee09091cfd7373a75926d2573c2f26"
  - filename: "ALL.chr14.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr14.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    checksum: "8eeee37c2f28b27f257534a8dc2eddcb51e515e4bbc685159045977f3c2d6f9d"
  - filename: "ALL.chr15.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr15.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    checksum: "844890f7879b36d7185cb13a49728244e93a14b87a3be66c31699b6f8959f6a0"
  - filename: "ALL.chr16.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr16.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    checksum: "e9acf0ada87823c96a6af8b409b5c41d107d44305db5ea8e050c2b629c94aa8a"
  - filename: "ALL.chr17.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr17.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    checksum: "1318fcf4b286735945dfc509da8f321fa4097dc44077fade94111171ce1e5272"
  - filename: "ALL.chr18.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr18.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    checksum: "0866db88bfb30a10f103c48413effe960a75eb9a13871236e9fcccb9de392f76"
  - filename: "ALL.chr19.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr19.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    checksum: "3a347dba71d8571ceadc6cd00d24119a87a04f040f211ae43cbc2cf3a1c748bd"
  - filename: "ALL.chr20.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr20.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    checksum: "d7728750b42dab8dd516887b0856f6c710c2be33ff732084d3056c0fb30ba98a"
  - filename: "ALL.chr21.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr21.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    checksum: "e87a55de3db734add587258c23f228bdc042323e2daf09ac4b7d18480b8de3a0"
  - filename: "ALL.chr22.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    url: "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr22.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz.tbi"
    checksum: "27de6b77af65d300bb968e8e372439deb949389e4395eb0dd251f9ba7d73bbed"
plink_files:
  prefix: 1000G.EUR.QC.
  EUR:
    filename: "1000G_Phase3_plinkfiles.tgz"
    url: "https://zenodo.org/records/7796478/files/1000G_Phase3_plinkfiles.tgz?download=1"
  EAS:
    filename: "1000G_Phase3_EAS_plinkfiles.tgz"
    url: "https://zenodo.org/records/7796478/files/1000G_Phase3_EAS_plinkfiles.tgz?download=1"
ld_scores:
  prefix: baselineLD.
  EUR:
    filename: "1000G_Phase3_baselineLD_v2.2_ldscores.tgz"
    url: "https://zenodo.org/records/10515792/files/1000G_Phase3_baselineLD_v2.2_ldscores.tgz?download=1"
  EAS:
    filename: "1000G_Phase3_EAS_baselineLD_v2.2_ldscores.tgz"
    url: "https://zenodo.org/records/10515792/files/1000G_Phase3_EAS_baselineLD_v2.2_ldscores.tgz?download=1"
ld_weights:
  prefix: weights.hm3_noMHC.
  EUR:
    filename: "1000G_Phase3_weights_hm3_no_MHC.tgz"
    url: "https://zenodo.org/records/10515792/files/1000G_Phase3_weights_hm3_no_MHC.tgz?download=1"
  EAS:
    filename: "1000G_Phase3_EAS_weights_hm3_no_MHC.tgz"
    url: "https://zenodo.org/records/10515792/files/1000G_Phase3_EAS_weights_hm3_no_MHC.tgz?download=1"
